apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-appication
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: "https://github.com/Snehalcg7/argocd"
    targetRevision: HEAD
    path: "application-files"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
