apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: "https://github.com/Snehalcg7/kubernetesfiles"
    targetRevision: master
    path: "files"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
